<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> b075bdc27629da6a3979fb3617d9e69ec56745b4
spring:
  datasource:
    url:
      jdbc:h2:mem:test
    username:
      username
    password:
      password
  h2:
    console:
      enabled:
        true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
<<<<<<< HEAD

=======
=======
spring.h2.console.enabled=true
>>>>>>> 340ecb7048c0f48fff224acc2070c8b38fb83786
>>>>>>> b075bdc27629da6a3979fb3617d9e69ec56745b4
