<<<<<<< HEAD
spring:
  datasource:
    url:
      jdbc:h2:mem:test
    username:
      username
    password:
      password
  h2:
    console:
      enabled:
        true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
=======
spring.h2.console.enabled=true
>>>>>>> 340ecb7048c0f48fff224acc2070c8b38fb83786
